title: "Network Commons"
description: "Technology, society, and security—resources and updates."
lang: en
theme: null
permalink: pretty
markdown: kramdown
kramdown: { input: GFM }
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
paginate: 10
paginate_path: "/page:num/"
defaults:
  - scope: { path: "" }
    values: { layout: default }
exclude: [ "README.md", "LICENSE", "Gemfile", "Gemfile.lock" ]
